/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited.
// It is generated by Next.js and holds type definitions for the Next.js API.
// Learn more: https://nextjs.org/docs/basic-features/typescript
